name: Build Go linux_amd64

on:
    workflow_dispatch:


jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main

    - name: Set up Go
      uses: actions/setup-go@main
      with:
        go-version: '1.22'

    # - name: Print Go version and environment
    #   id: vars
    #   run: |
    #     printf "Using go at: $(which go)\n"
    #     printf "Go version: $(go version)\n"
    #     printf "\n\nGo environment:\n\n"
    #     go env
    #     printf "\n\nSystem environment:\n\n"
    #     env
    #     echo "::set-output name=go_cache::$(go env GOCACHE)"

    # - name: Get dependencies
    #   run: go get -v -t -d ./...


    - name: Build webdav
      working-directory: .
      # env:
      #   CGO_ENABLED: 0
      run: GOOS=linux GOARCH=amd64 go build -trimpath -ldflags="-w -s" -v

      
    # - name: Build
    #   run: |
    #     sudo apt-get update -y
    #     sudo apt-get install make  -y
    #     sudo apt-get install iptables -y
    #     make
        
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@main
      with:
        name: webdav.zip
        path: webdav